### ISSUE TITLE
Unable to fetch public key from repo

### ISSUE THREAD

**Issue by smunj** [Azure/deploy-to-azure-cli-extension#46]
## Describe the bug

**Command Name**
`az container app up
Extension Name: deploy-to-azure. Version: 0.2.0.`

**Errors:**
```
'key'
Traceback (most recent call last):
pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 631, in execute
cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
cli\core\commands\__init__.py, ln 688, in _run_job
Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 665, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
...
    create_repo_secret(repo_name, 'AZURE_CREDENTIALS', auth_details_string)
azext_deploy_to_azure\dev\common\github_api_helper.py, ln 313, in create_repo_secret
    encrypted_text = encrypt_secret(key_details['key'], secret_value)
KeyError: 'key'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container app up --repository {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
azure-devops 0.18.0
deploy-to-azure 0.2.0

```
## Additional Context

Trying to get public key using PAT token. The error message says "Must have admin rights to repository", when I am trying to access my repo. Tried regenerating a new PAT token and giving all access required, but still no luck. Can anyone suggest what I should do

**Comment by benjick** [comment]
@smunj did you solve this?

**Comment by smunj** [comment]
What problem are you facing here. For me, it turned out that cli does not support pasting the PAT token using right mouse button click or CTRL+v on command prompt, hence PAT token was not getting passed properly. Please check if you are doing the same thing.

**Comment by benjick** [comment]
Seems the GITHUB_ is reserved (my guess, couldn't find it documented) so the secret was never created and I missed it. Just used `GH_PAT` instead
